export type UserReview = {
  id: string;
  title: string;
  text: string;
  time_of_use: string;
  price_paid: string;
  rating: number;
  rating_performance: number;
  rating_cost_benefit: number;
  rating_comfort: number;
  rating_weight: number;
  rating_durability: number;
  likes: number;
  dislikes: number;
  comments: number;
  images: string[];
  user_profile_img: string;
  user_name: string;
  store: string;
  badges: string[];
  created_at: string;
};
